### ISSUE TITLE
Umbrella 3.0

### ISSUE THREAD

**Issue by rpominov** [rpominov/kefir#138]
I think of work on 3.0 release in near future, but I won't have much time, and some features need further discussion / consideration. So I'd like to include in 3.0 only part of breaking changes we currently have planned.

Included:

 - [x] remove [all currently deprecated methods](https://github.com/rpominov/kefir/blob/master/deprecated-api-docs.md)
 - [x] fix .bufferBy & .bufferWhileBy #131
 - [x] fix property's current value in onValue handler #127
 - [x] deprecate .errorsToValues / .valuesToErrors in favor of .flatMap / .flatMapErrors #149
 - [x] remove `event.current` #100
 - [x] deprecate `.endOnError()` & add `.takeErrors(n)` similar to `.take(n)` #150
 - [x] Deprecate .awaiting? #145
 - [x] Should .flatten always return a stream? #144
 - [x] Rename .skipValues() and friends to .ignoreValues() #152

Not included:

 - .observe replacing .on\*/.of\* https://github.com/rpominov/kefir/issues/103#issuecomment-100713065
 - Don't do nested emits, use queue #120
 - Rethink meaning of "latest/previous value" #102
 - When property deactivates the current value of it should be removed #59

**Comment by rpominov** [comment]
Btw, if anyone want to help making this changes, you are very welcome. 
I've just created `3.0` branch to where PRs should be pointed, if any :)

We'll also need changes in docs, if anyone want to help with this. Although we probably need to update code first.

**Comment by rpominov** [comment]
`3.0.0-rc.0` is out in case someone want to try it before the final release.

**Comment by rpominov** [comment]
`3.0.0` is out now!
